sonar.projectKey=13SOAT-andromeda_tech-challenge-payments-api
sonar.organization=13soat-andromeda
sonar.projectName=tech-challenge-payments-api

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/openspec/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
