DATABASE_URL=postgres://payments:payments@postgres:5432/payments?sslmode=disable
SQS_QUEUE_URL_ORDER_EVENTS=http://localstack:4566/000000000000/payment-order-events-queue
SNS_TOPIC_ARN_PAYMENT=arn:aws:sns:us-east-1:000000000000:payment-events
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
PORT=8080
