apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: payments-api
    newName: ECR_IMAGE
    newTag: latest

resources:
  - ../../base

configMapGenerator:
  - name: payments-api-config
    envs:
      - .env.host
      - config.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: payments-api-secrets
    envs:
      - .env.secrets
    options:
      disableNameSuffixHash: true

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: payments-api
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
    target:
      kind: Deployment
      name: payments-api